// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: basic.proto

package basicv1

import (
	_ "github.com/go-sphere/binding/sphere/binding"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// BasicRequest exercises the per-field location override together with a
// message level default_location: fields without an explicit location fall back
// to QUERY.
type BasicRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	PathId      string                 `protobuf:"bytes,1,opt,name=path_id,json=pathId,proto3" json:"-" uri:"path_id"`
	HeaderToken string                 `protobuf:"bytes,2,opt,name=header_token,json=headerToken,proto3" json:"-" header:"header_token"`
	FormName    string                 `protobuf:"bytes,3,opt,name=form_name,json=formName,proto3" json:"-" form:"form_name"`
	// Falls back to the message default (QUERY).
	Keyword string `protobuf:"bytes,4,opt,name=keyword,proto3" json:"-" query:"keyword"`
	Page    int64  `protobuf:"varint,5,opt,name=page,proto3" json:"-" query:"page"`
	// JSON location keeps the original json tag and adds nothing.
	BodyNote      string `protobuf:"bytes,6,opt,name=body_note,json=bodyNote,proto3" json:"body_note,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BasicRequest) Reset() {
	*x = BasicRequest{}
	mi := &file_basic_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BasicRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BasicRequest) ProtoMessage() {}

func (x *BasicRequest) ProtoReflect() protoreflect.Message {
	mi := &file_basic_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BasicRequest.ProtoReflect.Descriptor instead.
func (*BasicRequest) Descriptor() ([]byte, []int) {
	return file_basic_proto_rawDescGZIP(), []int{0}
}

func (x *BasicRequest) GetPathId() string {
	if x != nil {
		return x.PathId
	}
	return ""
}

func (x *BasicRequest) GetHeaderToken() string {
	if x != nil {
		return x.HeaderToken
	}
	return ""
}

func (x *BasicRequest) GetFormName() string {
	if x != nil {
		return x.FormName
	}
	return ""
}

func (x *BasicRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *BasicRequest) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *BasicRequest) GetBodyNote() string {
	if x != nil {
		return x.BodyNote
	}
	return ""
}

type BasicResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            string                 `protobuf:"bytes,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BasicResponse) Reset() {
	*x = BasicResponse{}
	mi := &file_basic_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BasicResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BasicResponse) ProtoMessage() {}

func (x *BasicResponse) ProtoReflect() protoreflect.Message {
	mi := &file_basic_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BasicResponse.ProtoReflect.Descriptor instead.
func (*BasicResponse) Descriptor() ([]byte, []int) {
	return file_basic_proto_rawDescGZIP(), []int{1}
}

func (x *BasicResponse) GetOk() string {
	if x != nil {
		return x.Ok
	}
	return ""
}

var File_basic_proto protoreflect.FileDescriptor

const file_basic_proto_rawDesc = "" +
	"\n" +
	"\vbasic.proto\x12\x11testdata.basic.v1\x1a\x1csphere/binding/binding.proto\"\xda\x01\n" +
	"\fBasicRequest\x12\x1f\n" +
	"\apath_id\x18\x01 \x01(\tB\x06\xc0\x9d\xa6\x89\x04\x02R\x06pathId\x12)\n" +
	"\fheader_token\x18\x02 \x01(\tB\x06\xc0\x9d\xa6\x89\x04\x05R\vheaderToken\x12#\n" +
	"\tform_name\x18\x03 \x01(\tB\x06\xc0\x9d\xa6\x89\x04\x04R\bformName\x12\x18\n" +
	"\akeyword\x18\x04 \x01(\tR\akeyword\x12\x12\n" +
	"\x04page\x18\x05 \x01(\x03R\x04page\x12#\n" +
	"\tbody_note\x18\x06 \x01(\tB\x06\xc0\x9d\xa6\x89\x04\x03R\bbodyNote:\x06\xa0\x9c\xa6\x89\x04\x01\"\x1f\n" +
	"\rBasicResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\tR\x02okB^Z\\github.com/go-sphere/protoc-gen-sphere-binding/generate/binding/testdata/gen/basicv1;basicv1b\x06proto3"

var (
	file_basic_proto_rawDescOnce sync.Once
	file_basic_proto_rawDescData []byte
)

func file_basic_proto_rawDescGZIP() []byte {
	file_basic_proto_rawDescOnce.Do(func() {
		file_basic_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_basic_proto_rawDesc), len(file_basic_proto_rawDesc)))
	})
	return file_basic_proto_rawDescData
}

var file_basic_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_basic_proto_goTypes = []any{
	(*BasicRequest)(nil),  // 0: testdata.basic.v1.BasicRequest
	(*BasicResponse)(nil), // 1: testdata.basic.v1.BasicResponse
}
var file_basic_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_basic_proto_init() }
func file_basic_proto_init() {
	if File_basic_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_basic_proto_rawDesc), len(file_basic_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_basic_proto_goTypes,
		DependencyIndexes: file_basic_proto_depIdxs,
		MessageInfos:      file_basic_proto_msgTypes,
	}.Build()
	File_basic_proto = out.File
	file_basic_proto_goTypes = nil
	file_basic_proto_depIdxs = nil
}
