// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: integration.proto

package integrationv1

import (
	_ "github.com/go-sphere/binding/sphere/binding"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Item carries a map and a oneof in the JSON body. With no binding location set
// they keep their json tags and receive no query/uri/header/form tag.
type Item struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Name   string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value  int64                  `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	Labels map[string]string      `protobuf:"bytes,3,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Types that are valid to be assigned to Kind:
	//
	//	*Item_Text
	//	*Item_Number
	Kind          isItem_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Item) Reset() {
	*x = Item{}
	mi := &file_integration_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_integration_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_integration_proto_rawDescGZIP(), []int{0}
}

func (x *Item) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Item) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *Item) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *Item) GetKind() isItem_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *Item) GetText() string {
	if x != nil {
		if x, ok := x.Kind.(*Item_Text); ok {
			return x.Text
		}
	}
	return ""
}

func (x *Item) GetNumber() int64 {
	if x != nil {
		if x, ok := x.Kind.(*Item_Number); ok {
			return x.Number
		}
	}
	return 0
}

type isItem_Kind interface {
	isItem_Kind()
}

type Item_Text struct {
	Text string `protobuf:"bytes,4,opt,name=text,proto3,oneof"`
}

type Item_Number struct {
	Number int64 `protobuf:"varint,5,opt,name=number,proto3,oneof"`
}

func (*Item_Text) isItem_Kind() {}

func (*Item_Number) isItem_Kind() {}

// CreateItemRequest mixes uri / header / well-known query bindings with a nested
// message that must stay in the JSON body.
type CreateItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"-" uri:"tenant_id"`
	RequestId     string                 `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"-" header:"request_id"`
	NotBefore     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=not_before,json=notBefore,proto3" json:"-" query:"not_before"`
	Item          *Item                  `protobuf:"bytes,4,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateItemRequest) Reset() {
	*x = CreateItemRequest{}
	mi := &file_integration_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateItemRequest) ProtoMessage() {}

func (x *CreateItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_integration_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateItemRequest.ProtoReflect.Descriptor instead.
func (*CreateItemRequest) Descriptor() ([]byte, []int) {
	return file_integration_proto_rawDescGZIP(), []int{1}
}

func (x *CreateItemRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *CreateItemRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *CreateItemRequest) GetNotBefore() *timestamppb.Timestamp {
	if x != nil {
		return x.NotBefore
	}
	return nil
}

func (x *CreateItemRequest) GetItem() *Item {
	if x != nil {
		return x.Item
	}
	return nil
}

// UploadItemRequest defaults every field to FORM except the uri param.
type UploadItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"-" uri:"tenant_id"`
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"-" form:"filename"`
	Size          int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"-" form:"size"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadItemRequest) Reset() {
	*x = UploadItemRequest{}
	mi := &file_integration_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadItemRequest) ProtoMessage() {}

func (x *UploadItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_integration_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadItemRequest.ProtoReflect.Descriptor instead.
func (*UploadItemRequest) Descriptor() ([]byte, []int) {
	return file_integration_proto_rawDescGZIP(), []int{2}
}

func (x *UploadItemRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *UploadItemRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *UploadItemRequest) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

// ListItemsRequest binds well-known scalar wrappers as query params; these are
// allowed because they wrap a single scalar value.
type ListItemsRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	TenantId      string                  `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"-" uri:"tenant_id"`
	CreatedAfter  *timestamppb.Timestamp  `protobuf:"bytes,2,opt,name=created_after,json=createdAfter,proto3" json:"-" query:"created_after"`
	MaxAge        *durationpb.Duration    `protobuf:"bytes,3,opt,name=max_age,json=maxAge,proto3" json:"-" query:"max_age"`
	Keyword       *wrapperspb.StringValue `protobuf:"bytes,4,opt,name=keyword,proto3" json:"-" query:"keyword"`
	Limit         *wrapperspb.Int64Value  `protobuf:"bytes,5,opt,name=limit,proto3" json:"-" query:"limit"`
	Active        *wrapperspb.BoolValue   `protobuf:"bytes,6,opt,name=active,proto3" json:"-" query:"active"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListItemsRequest) Reset() {
	*x = ListItemsRequest{}
	mi := &file_integration_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListItemsRequest) ProtoMessage() {}

func (x *ListItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_integration_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListItemsRequest.ProtoReflect.Descriptor instead.
func (*ListItemsRequest) Descriptor() ([]byte, []int) {
	return file_integration_proto_rawDescGZIP(), []int{3}
}

func (x *ListItemsRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ListItemsRequest) GetCreatedAfter() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAfter
	}
	return nil
}

func (x *ListItemsRequest) GetMaxAge() *durationpb.Duration {
	if x != nil {
		return x.MaxAge
	}
	return nil
}

func (x *ListItemsRequest) GetKeyword() *wrapperspb.StringValue {
	if x != nil {
		return x.Keyword
	}
	return nil
}

func (x *ListItemsRequest) GetLimit() *wrapperspb.Int64Value {
	if x != nil {
		return x.Limit
	}
	return nil
}

func (x *ListItemsRequest) GetActive() *wrapperspb.BoolValue {
	if x != nil {
		return x.Active
	}
	return nil
}

var File_integration_proto protoreflect.FileDescriptor

const file_integration_proto_rawDesc = "" +
	"\n" +
	"\x11integration.proto\x12\x17testdata.integration.v1\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x1csphere/binding/binding.proto\"\xe6\x01\n" +
	"\x04Item\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value\x12A\n" +
	"\x06labels\x18\x03 \x03(\v2).testdata.integration.v1.Item.LabelsEntryR\x06labels\x12\x14\n" +
	"\x04text\x18\x04 \x01(\tH\x00R\x04text\x12\x18\n" +
	"\x06number\x18\x05 \x01(\x03H\x00R\x06number\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x06\n" +
	"\x04kind\"\xd5\x01\n" +
	"\x11CreateItemRequest\x12#\n" +
	"\ttenant_id\x18\x01 \x01(\tB\x06\xc0\x9d\xa6\x89\x04\x02R\btenantId\x12%\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tB\x06\xc0\x9d\xa6\x89\x04\x05R\trequestId\x12A\n" +
	"\n" +
	"not_before\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampB\x06\xc0\x9d\xa6\x89\x04\x01R\tnotBefore\x121\n" +
	"\x04item\x18\x04 \x01(\v2\x1d.testdata.integration.v1.ItemR\x04item\"p\n" +
	"\x11UploadItemRequest\x12#\n" +
	"\ttenant_id\x18\x01 \x01(\tB\x06\xc0\x9d\xa6\x89\x04\x02R\btenantId\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size:\x06\xa0\x9c\xa6\x89\x04\x04\"\xd3\x02\n" +
	"\x10ListItemsRequest\x12#\n" +
	"\ttenant_id\x18\x01 \x01(\tB\x06\xc0\x9d\xa6\x89\x04\x02R\btenantId\x12?\n" +
	"\rcreated_after\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\fcreatedAfter\x122\n" +
	"\amax_age\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\x06maxAge\x126\n" +
	"\akeyword\x18\x04 \x01(\v2\x1c.google.protobuf.StringValueR\akeyword\x121\n" +
	"\x05limit\x18\x05 \x01(\v2\x1b.google.protobuf.Int64ValueR\x05limit\x122\n" +
	"\x06active\x18\x06 \x01(\v2\x1a.google.protobuf.BoolValueR\x06active:\x06\xa0\x9c\xa6\x89\x04\x01BjZhgithub.com/go-sphere/protoc-gen-sphere-binding/generate/binding/testdata/gen/integrationv1;integrationv1b\x06proto3"

var (
	file_integration_proto_rawDescOnce sync.Once
	file_integration_proto_rawDescData []byte
)

func file_integration_proto_rawDescGZIP() []byte {
	file_integration_proto_rawDescOnce.Do(func() {
		file_integration_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_integration_proto_rawDesc), len(file_integration_proto_rawDesc)))
	})
	return file_integration_proto_rawDescData
}

var file_integration_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_integration_proto_goTypes = []any{
	(*Item)(nil),                   // 0: testdata.integration.v1.Item
	(*CreateItemRequest)(nil),      // 1: testdata.integration.v1.CreateItemRequest
	(*UploadItemRequest)(nil),      // 2: testdata.integration.v1.UploadItemRequest
	(*ListItemsRequest)(nil),       // 3: testdata.integration.v1.ListItemsRequest
	nil,                            // 4: testdata.integration.v1.Item.LabelsEntry
	(*timestamppb.Timestamp)(nil),  // 5: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),    // 6: google.protobuf.Duration
	(*wrapperspb.StringValue)(nil), // 7: google.protobuf.StringValue
	(*wrapperspb.Int64Value)(nil),  // 8: google.protobuf.Int64Value
	(*wrapperspb.BoolValue)(nil),   // 9: google.protobuf.BoolValue
}
var file_integration_proto_depIdxs = []int32{
	4, // 0: testdata.integration.v1.Item.labels:type_name -> testdata.integration.v1.Item.LabelsEntry
	5, // 1: testdata.integration.v1.CreateItemRequest.not_before:type_name -> google.protobuf.Timestamp
	0, // 2: testdata.integration.v1.CreateItemRequest.item:type_name -> testdata.integration.v1.Item
	5, // 3: testdata.integration.v1.ListItemsRequest.created_after:type_name -> google.protobuf.Timestamp
	6, // 4: testdata.integration.v1.ListItemsRequest.max_age:type_name -> google.protobuf.Duration
	7, // 5: testdata.integration.v1.ListItemsRequest.keyword:type_name -> google.protobuf.StringValue
	8, // 6: testdata.integration.v1.ListItemsRequest.limit:type_name -> google.protobuf.Int64Value
	9, // 7: testdata.integration.v1.ListItemsRequest.active:type_name -> google.protobuf.BoolValue
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_integration_proto_init() }
func file_integration_proto_init() {
	if File_integration_proto != nil {
		return
	}
	file_integration_proto_msgTypes[0].OneofWrappers = []any{
		(*Item_Text)(nil),
		(*Item_Number)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_integration_proto_rawDesc), len(file_integration_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_integration_proto_goTypes,
		DependencyIndexes: file_integration_proto_depIdxs,
		MessageInfos:      file_integration_proto_msgTypes,
	}.Build()
	File_integration_proto = out.File
	file_integration_proto_goTypes = nil
	file_integration_proto_depIdxs = nil
}
