// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: oneof.proto

package oneofv1

import (
	_ "github.com/go-sphere/binding/sphere/binding"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// OneofRequest exercises oneof level defaults plus nested messages, both of
// which inherit the location/auto_tags from their enclosing scope.
type OneofRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Outer string                 `protobuf:"bytes,1,opt,name=outer,proto3" json:"-" query:"outer"`
	// NOTE: protoc-gen-go emits each oneof member in its own wrapper struct
	// (OneofRequest_ByName), so the current plugin — which keys tags by the parent
	// message struct — leaves these fields untouched. The golden file captures
	// that behavior so any future fix shows up as a diff.
	//
	// Types that are valid to be assigned to Selector:
	//
	//	*OneofRequest_ByName
	//	*OneofRequest_ById
	Selector      isOneofRequest_Selector `protobuf_oneof:"selector"`
	Filter        *OneofRequest_Filter    `protobuf:"bytes,4,opt,name=filter,proto3" json:"-" query:"filter"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OneofRequest) Reset() {
	*x = OneofRequest{}
	mi := &file_oneof_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OneofRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OneofRequest) ProtoMessage() {}

func (x *OneofRequest) ProtoReflect() protoreflect.Message {
	mi := &file_oneof_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OneofRequest.ProtoReflect.Descriptor instead.
func (*OneofRequest) Descriptor() ([]byte, []int) {
	return file_oneof_proto_rawDescGZIP(), []int{0}
}

func (x *OneofRequest) GetOuter() string {
	if x != nil {
		return x.Outer
	}
	return ""
}

func (x *OneofRequest) GetSelector() isOneofRequest_Selector {
	if x != nil {
		return x.Selector
	}
	return nil
}

func (x *OneofRequest) GetByName() string {
	if x != nil {
		if x, ok := x.Selector.(*OneofRequest_ByName); ok {
			return x.ByName
		}
	}
	return ""
}

func (x *OneofRequest) GetById() int64 {
	if x != nil {
		if x, ok := x.Selector.(*OneofRequest_ById); ok {
			return x.ById
		}
	}
	return 0
}

func (x *OneofRequest) GetFilter() *OneofRequest_Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

type isOneofRequest_Selector interface {
	isOneofRequest_Selector()
}

type OneofRequest_ByName struct {
	ByName string `protobuf:"bytes,2,opt,name=by_name,json=byName,proto3,oneof"`
}

type OneofRequest_ById struct {
	ById int64 `protobuf:"varint,3,opt,name=by_id,json=byId,proto3,oneof"`
}

func (*OneofRequest_ByName) isOneofRequest_Selector() {}

func (*OneofRequest_ById) isOneofRequest_Selector() {}

type OneofResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            string                 `protobuf:"bytes,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OneofResponse) Reset() {
	*x = OneofResponse{}
	mi := &file_oneof_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OneofResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OneofResponse) ProtoMessage() {}

func (x *OneofResponse) ProtoReflect() protoreflect.Message {
	mi := &file_oneof_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OneofResponse.ProtoReflect.Descriptor instead.
func (*OneofResponse) Descriptor() ([]byte, []int) {
	return file_oneof_proto_rawDescGZIP(), []int{1}
}

func (x *OneofResponse) GetOk() string {
	if x != nil {
		return x.Ok
	}
	return ""
}

// Nested message inherits the enclosing message location (QUERY).
type OneofRequest_Filter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"-" query:"status"`
	Limit         int64                  `protobuf:"varint,2,opt,name=limit,proto3" json:"-" query:"limit"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OneofRequest_Filter) Reset() {
	*x = OneofRequest_Filter{}
	mi := &file_oneof_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OneofRequest_Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OneofRequest_Filter) ProtoMessage() {}

func (x *OneofRequest_Filter) ProtoReflect() protoreflect.Message {
	mi := &file_oneof_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OneofRequest_Filter.ProtoReflect.Descriptor instead.
func (*OneofRequest_Filter) Descriptor() ([]byte, []int) {
	return file_oneof_proto_rawDescGZIP(), []int{0, 0}
}

func (x *OneofRequest_Filter) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *OneofRequest_Filter) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

var File_oneof_proto protoreflect.FileDescriptor

const file_oneof_proto_rawDesc = "" +
	"\n" +
	"\voneof.proto\x12\x11testdata.oneof.v1\x1a\x1csphere/binding/binding.proto\"\xf8\x01\n" +
	"\fOneofRequest\x12\x14\n" +
	"\x05outer\x18\x01 \x01(\tR\x05outer\x12\x19\n" +
	"\aby_name\x18\x02 \x01(\tH\x00R\x06byName\x12\x15\n" +
	"\x05by_id\x18\x03 \x01(\x03H\x00R\x04byId\x12>\n" +
	"\x06filter\x18\x04 \x01(\v2&.testdata.oneof.v1.OneofRequest.FilterR\x06filter\x1a6\n" +
	"\x06Filter\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x03R\x05limit:\x06\xa0\x9c\xa6\x89\x04\x01B \n" +
	"\bselector\x12\x14\U0001c989\x04\x02\xfa\x9c\xa6\x89\x04\bvalidate\"\x1f\n" +
	"\rOneofResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\tR\x02okB^Z\\github.com/go-sphere/protoc-gen-sphere-binding/generate/binding/testdata/gen/oneofv1;oneofv1b\x06proto3"

var (
	file_oneof_proto_rawDescOnce sync.Once
	file_oneof_proto_rawDescData []byte
)

func file_oneof_proto_rawDescGZIP() []byte {
	file_oneof_proto_rawDescOnce.Do(func() {
		file_oneof_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_oneof_proto_rawDesc), len(file_oneof_proto_rawDesc)))
	})
	return file_oneof_proto_rawDescData
}

var file_oneof_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_oneof_proto_goTypes = []any{
	(*OneofRequest)(nil),        // 0: testdata.oneof.v1.OneofRequest
	(*OneofResponse)(nil),       // 1: testdata.oneof.v1.OneofResponse
	(*OneofRequest_Filter)(nil), // 2: testdata.oneof.v1.OneofRequest.Filter
}
var file_oneof_proto_depIdxs = []int32{
	2, // 0: testdata.oneof.v1.OneofRequest.filter:type_name -> testdata.oneof.v1.OneofRequest.Filter
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_oneof_proto_init() }
func file_oneof_proto_init() {
	if File_oneof_proto != nil {
		return
	}
	file_oneof_proto_msgTypes[0].OneofWrappers = []any{
		(*OneofRequest_ByName)(nil),
		(*OneofRequest_ById)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_oneof_proto_rawDesc), len(file_oneof_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_oneof_proto_goTypes,
		DependencyIndexes: file_oneof_proto_depIdxs,
		MessageInfos:      file_oneof_proto_msgTypes,
	}.Build()
	File_oneof_proto = out.File
	file_oneof_proto_goTypes = nil
	file_oneof_proto_depIdxs = nil
}
