// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: tags.proto

package tagsv1

import (
	_ "github.com/go-sphere/binding/sphere/binding"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TagsRequest exercises auto_tags and manual tags overrides.
type TagsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Inherits the default_auto_tags ("validate") only.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty" validate:"name"`
	// Manual tags win over everything: they overwrite the generated json/validate
	// tags for this field.
	Nickname string `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nick" validate:"required"`
	// Field level auto_tags replaces the message default for this field.
	Email string `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty" form:"email"`
	// Location plus auto_tags combine: uri tag + the inherited validate tag.
	Id            string `protobuf:"bytes,4,opt,name=id,proto3" json:"-" uri:"id" validate:"id"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TagsRequest) Reset() {
	*x = TagsRequest{}
	mi := &file_tags_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TagsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagsRequest) ProtoMessage() {}

func (x *TagsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tags_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagsRequest.ProtoReflect.Descriptor instead.
func (*TagsRequest) Descriptor() ([]byte, []int) {
	return file_tags_proto_rawDescGZIP(), []int{0}
}

func (x *TagsRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TagsRequest) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *TagsRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *TagsRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type TagsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            string                 `protobuf:"bytes,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TagsResponse) Reset() {
	*x = TagsResponse{}
	mi := &file_tags_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TagsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagsResponse) ProtoMessage() {}

func (x *TagsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tags_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagsResponse.ProtoReflect.Descriptor instead.
func (*TagsResponse) Descriptor() ([]byte, []int) {
	return file_tags_proto_rawDescGZIP(), []int{1}
}

func (x *TagsResponse) GetOk() string {
	if x != nil {
		return x.Ok
	}
	return ""
}

var File_tags_proto protoreflect.FileDescriptor

const file_tags_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"tags.proto\x12\x10testdata.tags.v1\x1a\x1csphere/binding/binding.proto\"\xb3\x01\n" +
	"\vTagsRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12F\n" +
	"\bnickname\x18\x02 \x01(\tB*ʝ\xa6\x89\x04\vjson:\"nick\"ʝ\xa6\x89\x04\x13validate:\"required\"R\bnickname\x12 \n" +
	"\x05email\x18\x03 \x01(\tB\n" +
	"ҝ\xa6\x89\x04\x04formR\x05email\x12\x16\n" +
	"\x02id\x18\x04 \x01(\tB\x06\xc0\x9d\xa6\x89\x04\x02R\x02id:\x0e\xaa\x9c\xa6\x89\x04\bvalidate\"\x1e\n" +
	"\fTagsResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\tR\x02okB\\ZZgithub.com/go-sphere/protoc-gen-sphere-binding/generate/binding/testdata/gen/tagsv1;tagsv1b\x06proto3"

var (
	file_tags_proto_rawDescOnce sync.Once
	file_tags_proto_rawDescData []byte
)

func file_tags_proto_rawDescGZIP() []byte {
	file_tags_proto_rawDescOnce.Do(func() {
		file_tags_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tags_proto_rawDesc), len(file_tags_proto_rawDesc)))
	})
	return file_tags_proto_rawDescData
}

var file_tags_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_tags_proto_goTypes = []any{
	(*TagsRequest)(nil),  // 0: testdata.tags.v1.TagsRequest
	(*TagsResponse)(nil), // 1: testdata.tags.v1.TagsResponse
}
var file_tags_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_tags_proto_init() }
func file_tags_proto_init() {
	if File_tags_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tags_proto_rawDesc), len(file_tags_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tags_proto_goTypes,
		DependencyIndexes: file_tags_proto_depIdxs,
		MessageInfos:      file_tags_proto_msgTypes,
	}.Build()
	File_tags_proto = out.File
	file_tags_proto_goTypes = nil
	file_tags_proto_depIdxs = nil
}
